### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by stepech** [FireController1847/TrueDiscordLink#2]
Hello, I really love your plugin. I like how it translates messages into webhooks instead of typing them just as bot - making it seem more like the actual player wrote it, but:

the gamebreaker for me is the support for cyrillic and other characters. Characters like ě,š,č,ř,ž and probably more are translated just as "?" into discord chat. Can you change the formating from ASCI to UTF-8 to be more compatible when used in eastern countries?
Thanks

**Comment by FireController1847** [comment]
Hi there, thanks for the report. I wasn't even aware that this was an issue, though I suppose I didn't test with it. I'll take a look next time I get the chance.

**Comment by stepech** [comment]
Hey, I'm just a beginner but I wanted to learn a bit so I was going through the code to learn the syntax, etc. Trying to find the place where it is converted from UTF-8 as a challenge for me. I am sorry if I'm too intrusive, just want to ask to better understand.

Is the core of the problem in src/main/java/com/firecontroller1847/truediscordlink/DiscordManager.java
Line 392, 397?
Would it be repaired with `byte[] data = object.toString().getBytes("UTF8")` and `connection.setRequestProperty("Content-Type", "application/json; charset=utf-8");` respectively?

**Comment by FireController1847** [comment]
That very well appears to be it. When I go through I'll make sure there are no other references to ASCII, and then I'll apply the change

**Comment by FireController1847** [comment]
You'll find this to be fixed in the latest release v1.0.4 (yet to be released, should be in 10-20 minutes)
