### ISSUE TITLE
Channel Notification Upon Linkage

### ISSUE THREAD

**Issue by FireController1847** [FireController1847/TrueDiscordLink#3]
Add a feature where, when a player links their account, it sends a message to a channel configured in the config

**Comment by ItzNxthaniel** [comment]
Thoughts on it using a list of channels?

**Comment by FireController1847** [comment]
Kinda neutral on that one. I don't personally see sending to multiple channels the same message being useful, however if you're able to find a coherent way in which the message could be different depending on the channel, I think it could work.

**Comment by ItzNxthaniel** [comment]
If we want to go with the idea of a list of channels, we could use the same format as your `guildid:roleid`, but instead `channelid:message string` so for example: `000:{player} has linked their account with {tag}`? Player = MC Username, Tag = Discord Tag (<@000>).

This could definitely work, but maybe it's not fully needed, and I can just do a single channel method.
