### ISSUE TITLE
Advancements are broken entirely (NMS has changed)

### ISSUE THREAD

**Issue by FireController1847** [FireController1847/TrueDiscordLink#6]
Accessing NMS has changed since Spigot has switched to Mojang mappings, my reflection approach currently does not work. I don't know how the classes have changed or how to go about fixing this yet. See the following Spigot post for a description of what's changed about NMS:

https://www.spigotmc.org/threads/spigot-bungeecord-1-17-1-17-1.510208/

Also an informational page on NMS for 1.16+:

https://www.spigotmc.org/wiki/spigot-nms-and-minecraft-versions-1-16/

**Comment by ItzNxthaniel** [comment]
Only creating this, because you know I'm gonna fix it. 😂
![image](https://user-images.githubusercontent.com/11449808/147535246-21ee8b81-f6ce-4dde-9541-eab013a622c8.png)

**Comment by FireController1847** [comment]
Fixed in https://github.com/FireController1847/TrueDiscordLink/commit/3adf5c540b583057ddbbe2af08218cd9d0aca44e
